### ISSUE TITLE
Implementation of Anticor-1 algorithm 

### ISSUE THREAD

**Issue by petr-fedorov** [OLPS/OLPS#2]
It is not possible to reproduce ANTI-1 results from the original article A. Borodin et all "Borodin, A., El-aniv, R., & Gogan, V. (2004). Can We Learn to Beat the Best Stock. Journal of Artificial Intelligence Research, 21(1), 579–594. Retrieved from http://eprints.pascal-network.org/archive/00000229/" using algorithm Anticor-1 in OLPS. 
In particular Figure 2 (d) in the aforementioned article shows results of ANTI-1 on DJIA dataset. OLPS instead gives the following revenues for the first 10 windows:
2 - 0.96, 3 - 1.29, 4 - 1.37, 5 - 1.56, 6 - 1.59 7 - 1.58, 8 - 1.51, 9 - 1.50 , 10 - 1.51. These are obviously different from the article.

**Comment by binliwhu** [comment]
The problem in this issue is that the anticor.m represents BAH(Anticor) or Anti1, and anticor_anticor.m is BAH(Anticor(Anticor)). For the original anticor, please refer to anticor_expert.m. Therefore, the outputs in your description are the buy and hold version of Anticor, or ANTI1's outputs. But the figure 2 in the paper  is the wealth achieved by the original anticor algorithm (not ANTI1). You can output individual anticor expert's wealth by slightly modifying anticor.m. My outputs for the first 10 windows are as follows: 
0.964422277317538
1.61870012598612
1.55202299647211
2.10731851752921
1.71138741694993
1.51063799658284
1.12842307214487
1.37564746079815
1.64677022819734
